-- Primeiro testa o select para conferir se vai puxar os dados corretamente

SELECT
    PONTE.*
FROM dbo.CLIENTES_TRATADOS AS PONTE
WHERE
    ISNULL(NULLIF(LTRIM(RTRIM(PONTE.CPFCNPJ)), ''), '') <> ''
    AND NOT EXISTS (
        SELECT 1
        FROM dbo.CADASTRO_PESSOAS AS PESSOA
        WHERE PESSOA.CPFCNPJ = PONTE.CPFCNPJ
    );

-- Agora já pode fazer o insert

INSERT INTO dbo.CADASTRO_PESSOAS (
    TIPOPESSOA,
    CLIENTE,
    FORNECEDOR,
    SEXO,
    CPFCNPJ,
    RG,
    IE,
    IM,
    REGIMETRIBUTARIO,
    CONTRIBUINTE,
    NAOCONTRIBUINTE,
    SIMPLESNACIONAL,
    TRANSPORTADORA,
    NOME,
    FANTASIA,
    LOGRADOURO,
    ENDERECO,
    NUMERO,
    COMPLEMENTO,
    REFERENCIA,
    BAIRRO,
    CEP,
    CIDADE,
    IBGE,
    UF,
    DDD,
    TELEFONE,
    FAX,
    CELULAR,
    EMAIL,
    CONTATO,
    LIMITECOMPRA,
    CONTACONTABIL,
    DATACRIACAO,
    CRIADOPOR,
    DATAALTERACAO,
    ALTERADOPOR
)
SELECT
    1 AS TIPOPESSOA,
    1 AS CLIENTE,
    0 AS FORNECEDOR,
    '' AS SEXO,

    LEFT(ISNULL(NULLIF(LTRIM(RTRIM(PONTE.CPFCNPJ)), ''), ''), 14) AS CPFCNPJ,

    '' AS RG,
    '' AS IE,
    '' AS IM,

    0 AS REGIMETRIBUTARIO,
    0 AS CONTRIBUINTE,
    0 AS NAOCONTRIBUINTE,
    0 AS SIMPLESNACIONAL,
    0 AS TRANSPORTADORA,

    LEFT(ISNULL(NULLIF(LTRIM(RTRIM(PONTE.NOME)), ''), ''), 150) AS NOME,

    LEFT(ISNULL(NULLIF(LTRIM(RTRIM(PONTE.[RAZAO SOCIAL])), ''), ''), 150) AS FANTASIA,

    '' AS LOGRADOURO,
    '' AS ENDERECO,
    '' AS NUMERO,
    '' AS COMPLEMENTO,
    '' AS REFERENCIA,
    '' AS BAIRRO,

    LEFT(ISNULL(NULLIF(LTRIM(RTRIM(PONTE.CEP)), ''), ''), 8) AS CEP,

    LEFT(ISNULL(NULLIF(LTRIM(RTRIM(PONTE.CIDADE)), ''), ''), 150) AS CIDADE,

    '' AS IBGE,

    LEFT(ISNULL(NULLIF(LTRIM(RTRIM(PONTE.UF)), ''), ''), 2) AS UF,

    '' AS DDD,

    LEFT(ISNULL(NULLIF(LTRIM(RTRIM(PONTE.TELEFONE)), ''), ''), 10) AS TELEFONE,

    '' AS FAX,
    '' AS CELULAR,
    '' AS EMAIL,
    '' AS CONTATO,

    ISNULL(CAST(PONTE.LIMITE AS DECIMAL(18, 0)), 0) AS LIMITECOMPRA,

    -1 AS CONTACONTABIL,

    GETDATE() AS DATACRIACAO,
    1 AS CRIADOPOR,
    GETDATE() AS DATAALTERACAO,
    1 AS ALTERADOPOR

FROM dbo.CLIENTES_TRATADOS AS PONTE
WHERE
    ISNULL(NULLIF(LTRIM(RTRIM(PONTE.CPFCNPJ)), ''), '') <> ''
    AND NOT EXISTS (
        SELECT 1
        FROM dbo.CADASTRO_PESSOAS AS PESSOA
        WHERE PESSOA.CPFCNPJ = PONTE.CPFCNPJ
    );